$background = 040301
$onBackground = efe4d1
$surface = 040301
$surfaceDim = 040301
$surfaceBright = 0f0d06
$surfaceContainerLowest = 000000
$surfaceContainerLow = 060402
$surfaceContainer = 080603
$surfaceContainerHigh = 0b0904
$surfaceContainerHighest = 0d0b05
$onSurface = efe4d1
$surfaceVariant = 0d0b05
$onSurfaceVariant = b3aa98
$outline = 7c7565
$outlineVariant = 4d4739
$inverseSurface = fff8f0
$inverseOnSurface = 59554c
$shadow = 000000
$scrim = 000000
$surfaceTint = 2e2712
$primary = dcc587
$primaryDim = cdb77b
$onPrimary = 4e3f0e
$primaryContainer = 61511f
$onPrimaryContainer = fae1a1
$inversePrimary = 6f5d2a
$primaryFixed = f9e1a1
$primaryFixedDim = ead294
$onPrimaryFixed = 4d3e0d
$onPrimaryFixedVariant = 6b5a27
$secondary = d5c5a1
$secondaryDim = c6b894
$onSecondary = 493f24
$secondaryContainer = 443b1f
$onSecondaryContainer = cdbe9a
$secondaryFixed = f1e1bb
$secondaryFixedDim = e3d3ae
$onSecondaryFixed = 483e23
$onSecondaryFixedVariant = 665b3d
$tertiary = ffd5b4
$tertiaryDim = fec392
$onTertiary = 6e451f
$tertiaryContainer = fec392
$onTertiaryContainer = 643d17
$tertiaryFixed = fec392
$tertiaryFixedDim = efb586
$onTertiaryFixed = 4d2a05
$onTertiaryFixedVariant = 6e451f
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 887540
$secondaryPaletteKeyColor = 827656
$tertiaryPaletteKeyColor = 9c6d43
$neutralPaletteKeyColor = 7b766d
$neutralVariantPaletteKeyColor = 7e7666
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 887540
$secondary_paletteKeyColor = 827656
$tertiary_paletteKeyColor = 9c6d43
$neutral_paletteKeyColor = 7b766d
$neutral_variant_paletteKeyColor = 7e7666
$term0 = 080808
$term1 = c08600
$term2 = ecc944
$term3 = ffe3a4
$term4 = acae6d
$term5 = dd9e48
$term6 = d8cb71
$term7 = e4d7bf
$term8 = aca18f
$term9 = df9c00
$term10 = ffdb4e
$term11 = fff3dc
$term12 = c7c396
$term13 = ecb56a
$term14 = eedc77
$term15 = ffffff
$rosewater = fdefe0
$flamingo = f6dec0
$pink = ffd6aa
$mauve = ffad7f
$red = eaa740
$maroon = e7b672
$peach = efc87e
$yellow = fff0cf
$green = f2e17a
$teal = e6e490
$sky = dae18a
$sapphire = b3d27e
$blue = 75cf9d
$lavender = ffbcbb
$klink = 559652
$klinkSelection = 559652
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = b67d00
$knegativeSelection = b67d00
$kneutral = dba100
$kneutralSelection = dba100
$kpositive = baab00
$kpositiveSelection = baab00
$text = efe4d1
$subtext1 = b3aa98
$subtext0 = 7c7565
$overlay2 = 1a1917
$overlay1 = 171614
$overlay0 = 141310
$surface2 = 110f0c
$surface1 = 0c0b07
$surface0 = 060402
$base = 000000
$mantle = 000000
$crust = 000000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
